### ISSUE TITLE
LGPL

### ISSUE THREAD

**Issue by jayvdb** [gappleto97/CITest#11]
LGPL isnt a very suitable choice for reusability, as it will conflict with existing projects choice.

**Comment by LivInTheLookingGlass** [comment]
You're probably right. I was going through and changing all the licenses, but this one should be permissive. I'll throw it under MIT.

**Comment by LivInTheLookingGlass** [comment]
Should I close, or is this also a bad choice?

**Comment by jayvdb** [comment]
Much better; the issue is resolved as far as I am concerned as MIT is liberal enough for most users of this. A public domainish license would be better again, but up to you on that one.

**Comment by LivInTheLookingGlass** [comment]
My impression is that public domain licenses don't work everywhere, and that most have the MIT at the end for contingency.
